// Code generated by depgen; DO NOT EDIT.
// Source: terraform-provider-aws v1.52.0

package tfaws

import "github.com/LuminalHQ/cloudcover/x/tfx"

var depMap = tfx.DepMap{
	"aws_acm_certificate_validation": {
		{Attr: "certificate_arn", SrcType: "aws_acm_certificate", SrcAttr: "arn"},
		{Attr: "validation_record_fqdns", SrcType: "aws_route53_record", SrcAttr: "fqdn"},
	},
	"aws_acmpca_certificate_authority": {
		{Attr: "revocation_configuration.crl_configuration.s3_bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "id"},
	},
	"aws_alb": {
		{Attr: "security_groups", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "subnets", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_alb_listener_rule": {
		{Attr: "action.target_group_arn", SrcType: "aws_alb_target_group", SrcAttr: "arn"},
		{Attr: "listener_arn", SrcType: "aws_alb_listener", SrcAttr: "arn"},
	},
	"aws_alb_target_group": {
		{Attr: "name", SrcType: "aws_alb", SrcAttr: "name"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_alb_target_group_attachment": {
		{Attr: "target_group_arn", SrcType: "aws_alb_target_group", SrcAttr: "arn"},
		{Attr: "target_id", SrcType: "aws_instance", SrcAttr: "id"},
	},
	"aws_ami": {
		{Attr: "ebs_block_device.snapshot_id", SrcType: "aws_ebs_snapshot", SrcAttr: "id"},
	},
	"aws_ami_copy": {
		{Attr: "source_ami_id", SrcType: "aws_ami", SrcAttr: "id"},
	},
	"aws_ami_launch_permission": {
		{Attr: "image_id", SrcType: "aws_ami_copy", SrcAttr: "id"},
	},
	"aws_api_gateway_account": {
		{Attr: "cloudwatch_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_api_gateway_api_key": {
		{Attr: "stage_key.rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
		{Attr: "stage_key.stage_name", SrcType: "aws_api_gateway_deployment", SrcAttr: "stage_name"},
	},
	"aws_api_gateway_authorizer": {
		{Attr: "authorizer_credentials", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "authorizer_uri", SrcType: "aws_lambda_function", SrcAttr: "invoke_arn"},
		{Attr: "provider_arns", SrcType: "aws_cognito_user_pool", SrcAttr: "arn"},
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_base_path_mapping": {
		{Attr: "api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
		{Attr: "domain_name", SrcType: "aws_api_gateway_domain_name", SrcAttr: "domain_name"},
		{Attr: "stage_name", SrcType: "aws_api_gateway_deployment", SrcAttr: "stage_name"},
	},
	"aws_api_gateway_deployment": {
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_documentation_part": {
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_documentation_version": {
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_domain_name": {
		{Attr: "certificate_arn", SrcType: "aws_acm_certificate_validation", SrcAttr: "certificate_arn"},
		{Attr: "certificate_body", SrcType: "tls_locally_signed_cert", SrcAttr: "cert_pem"},
		{Attr: "certificate_chain", SrcType: "tls_self_signed_cert", SrcAttr: "cert_pem"},
		{Attr: "certificate_private_key", SrcType: "tls_private_key", SrcAttr: "private_key_pem"},
		{Attr: "regional_certificate_arn", SrcType: "aws_acm_certificate_validation", SrcAttr: "certificate_arn"},
	},
	"aws_api_gateway_gateway_response": {
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_integration": {
		{Attr: "connection_id", SrcType: "aws_api_gateway_vpc_link", SrcAttr: "id"},
		{Attr: "http_method", SrcType: "aws_api_gateway_method", SrcAttr: "http_method"},
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_integration_response": {
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
		{Attr: "status_code", SrcType: "aws_api_gateway_method_response", SrcAttr: "status_code"},
	},
	"aws_api_gateway_method": {
		{Attr: "authorizer_id", SrcType: "aws_api_gateway_authorizer", SrcAttr: "id"},
		{Attr: "request_validator_id", SrcType: "aws_api_gateway_request_validator", SrcAttr: "id"},
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_method_response": {
		{Attr: "http_method", SrcType: "aws_api_gateway_method", SrcAttr: "http_method"},
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_method_settings": {
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_model": {
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_request_validator": {
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_resource": {
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_stage": {
		{Attr: "access_log_settings.destination_arn", SrcType: "aws_cloudwatch_log_group", SrcAttr: "arn"},
		{Attr: "deployment_id", SrcType: "aws_api_gateway_deployment", SrcAttr: "id"},
		{Attr: "documentation_version", SrcType: "aws_api_gateway_documentation_version", SrcAttr: "version"},
		{Attr: "rest_api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
	},
	"aws_api_gateway_usage_plan": {
		{Attr: "api_stages.api_id", SrcType: "aws_api_gateway_rest_api", SrcAttr: "id"},
		{Attr: "api_stages.stage", SrcType: "aws_api_gateway_deployment", SrcAttr: "stage_name"},
	},
	"aws_api_gateway_usage_plan_key": {
		{Attr: "key_id", SrcType: "aws_api_gateway_api_key", SrcAttr: "id"},
		{Attr: "usage_plan_id", SrcType: "aws_api_gateway_usage_plan", SrcAttr: "id"},
	},
	"aws_api_gateway_vpc_link": {
		{Attr: "target_arns", SrcType: "aws_lb", SrcAttr: "arn"},
	},
	"aws_appautoscaling_policy": {
		{Attr: "scalable_dimension", SrcType: "aws_appautoscaling_target", SrcAttr: "scalable_dimension"},
		{Attr: "service_namespace", SrcType: "aws_appautoscaling_target", SrcAttr: "service_namespace"},
	},
	"aws_appautoscaling_scheduled_action": {
		{Attr: "resource_id", SrcType: "aws_appautoscaling_target", SrcAttr: "resource_id"},
		{Attr: "scalable_dimension", SrcType: "aws_appautoscaling_target", SrcAttr: "scalable_dimension"},
		{Attr: "service_namespace", SrcType: "aws_appautoscaling_target", SrcAttr: "service_namespace"},
	},
	"aws_appautoscaling_target": {
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_appmesh_route": {
		{Attr: "mesh_name", SrcType: "aws_appmesh_mesh", SrcAttr: "id"},
		{Attr: "spec.http_route.action.weighted_target.virtual_node", SrcType: "aws_appmesh_virtual_node", SrcAttr: "name"},
		{Attr: "virtual_router_name", SrcType: "aws_appmesh_virtual_router", SrcAttr: "name"},
	},
	"aws_appmesh_virtual_node": {
		{Attr: "mesh_name", SrcType: "aws_appmesh_mesh", SrcAttr: "id"},
	},
	"aws_appmesh_virtual_router": {
		{Attr: "mesh_name", SrcType: "aws_appmesh_mesh", SrcAttr: "id"},
	},
	"aws_appsync_api_key": {
		{Attr: "api_id", SrcType: "aws_appsync_graphql_api", SrcAttr: "id"},
	},
	"aws_appsync_datasource": {
		{Attr: "api_id", SrcType: "aws_appsync_graphql_api", SrcAttr: "id"},
		{Attr: "dynamodb_config.table_name", SrcType: "aws_dynamodb_table", SrcAttr: "name"},
		{Attr: "lambda_config.function_arn", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "service_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_appsync_graphql_api": {
		{Attr: "log_config.cloudwatch_logs_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "user_pool_config.user_pool_id", SrcType: "aws_cognito_user_pool", SrcAttr: "id"},
	},
	"aws_athena_database": {
		{Attr: "bucket", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "encryption_configuration.kms_key", SrcType: "aws_kms_key", SrcAttr: "arn"},
	},
	"aws_athena_named_query": {
		{Attr: "database", SrcType: "aws_athena_database", SrcAttr: "name"},
	},
	"aws_autoscaling_attachment": {
		{Attr: "autoscaling_group_name", SrcType: "aws_autoscaling_group", SrcAttr: "id"},
		{Attr: "elb", SrcType: "aws_elb", SrcAttr: "id"},
	},
	"aws_autoscaling_group": {
		{Attr: "availability_zones", SrcType: "aws_subnet", SrcAttr: "availability_zone"},
		{Attr: "launch_template.id", SrcType: "aws_launch_template", SrcAttr: "id"},
		{Attr: "load_balancers", SrcType: "aws_elb", SrcAttr: "name"},
		{Attr: "mixed_instances_policy.launch_template.launch_template_specification.launch_template_id", SrcType: "aws_launch_template", SrcAttr: "id"},
		{Attr: "mixed_instances_policy.launch_template.launch_template_specification.launch_template_name", SrcType: "aws_launch_template", SrcAttr: "name"},
		{Attr: "target_group_arns", SrcType: "aws_lb_target_group", SrcAttr: "arn"},
		{Attr: "vpc_zone_identifier", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_autoscaling_lifecycle_hook": {
		{Attr: "autoscaling_group_name", SrcType: "aws_autoscaling_group", SrcAttr: "name"},
		{Attr: "notification_target_arn", SrcType: "aws_sqs_queue", SrcAttr: "arn"},
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_autoscaling_notification": {
		{Attr: "group_names", SrcType: "aws_autoscaling_group", SrcAttr: "name"},
		{Attr: "topic_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_autoscaling_policy": {
		{Attr: "autoscaling_group_name", SrcType: "aws_autoscaling_group", SrcAttr: "name"},
	},
	"aws_autoscaling_schedule": {
		{Attr: "autoscaling_group_name", SrcType: "aws_autoscaling_group", SrcAttr: "name"},
	},
	"aws_batch_compute_environment": {
		{Attr: "compute_resources.security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "compute_resources.spot_iam_fleet_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "compute_resources.subnets", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "service_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_batch_job_queue": {
		{Attr: "compute_environments", SrcType: "aws_batch_compute_environment", SrcAttr: "arn"},
	},
	"aws_cloud9_environment_ec2": {
		{Attr: "owner_arn", SrcType: "aws_iam_user", SrcAttr: "arn"},
		{Attr: "subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_cloudformation_stack": {
		{Attr: "notification_arns", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_cloudfront_distribution": {
		{Attr: "ordered_cache_behavior.lambda_function_association.lambda_arn", SrcType: "aws_lambda_function", SrcAttr: "qualified_arn"},
	},
	"aws_cloudhsm_v2_cluster": {
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_cloudhsm_v2_hsm": {
		{Attr: "cluster_id", SrcType: "aws_cloudhsm_v2_cluster", SrcAttr: "cluster_id"},
		{Attr: "subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_cloudtrail": {
		{Attr: "cloud_watch_logs_group_arn", SrcType: "aws_cloudwatch_log_group", SrcAttr: "arn"},
		{Attr: "cloud_watch_logs_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "s3_bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "id"},
	},
	"aws_cloudwatch_event_permission": {
		{Attr: "condition.value", SrcType: "aws_organizations_organization", SrcAttr: "id"},
	},
	"aws_cloudwatch_event_rule": {
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_cloudwatch_event_target": {
		{Attr: "batch_target.job_definition", SrcType: "aws_batch_job_definition", SrcAttr: "arn"},
		{Attr: "ecs_target.network_configuration.subnets", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "ecs_target.task_definition_arn", SrcType: "aws_ecs_task_definition", SrcAttr: "arn"},
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_cloudwatch_log_destination": {
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "target_arn", SrcType: "aws_kinesis_stream", SrcAttr: "arn"},
	},
	"aws_cloudwatch_log_destination_policy": {
		{Attr: "destination_name", SrcType: "aws_cloudwatch_log_destination", SrcAttr: "name"},
	},
	"aws_cloudwatch_log_group": {
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
	},
	"aws_cloudwatch_log_metric_filter": {
		{Attr: "log_group_name", SrcType: "aws_cloudwatch_log_group", SrcAttr: "name"},
	},
	"aws_cloudwatch_log_subscription_filter": {
		{Attr: "log_group_name", SrcType: "aws_cloudwatch_log_group", SrcAttr: "name"},
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_cloudwatch_metric_alarm": {
		{Attr: "dimensions.AutoScalingGroupName", SrcType: "aws_autoscaling_group", SrcAttr: "name"},
		{Attr: "dimensions.InstanceId", SrcType: "aws_instance", SrcAttr: "id"},
	},
	"aws_codebuild_project": {
		{Attr: "artifacts.location", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "cache.location", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "encryption_key", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "secondary_artifacts.location", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "service_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "vpc_config.security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "vpc_config.subnets", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "vpc_config.vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_codebuild_webhook": {
		{Attr: "project_name", SrcType: "aws_codebuild_project", SrcAttr: "name"},
	},
	"aws_codecommit_trigger": {
		{Attr: "trigger.destination_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_codedeploy_deployment_group": {
		{Attr: "app_name", SrcType: "aws_codedeploy_app", SrcAttr: "name"},
		{Attr: "autoscaling_groups", SrcType: "aws_autoscaling_group", SrcAttr: "name"},
		{Attr: "deployment_config_name", SrcType: "aws_codedeploy_deployment_config", SrcAttr: "id"},
		{Attr: "ecs_service.cluster_name", SrcType: "aws_ecs_cluster", SrcAttr: "name"},
		{Attr: "ecs_service.service_name", SrcType: "aws_ecs_service", SrcAttr: "name"},
		{Attr: "load_balancer_info.elb_info.name", SrcType: "aws_elb", SrcAttr: "name"},
		{Attr: "load_balancer_info.target_group_pair_info.prod_traffic_route.listener_arns", SrcType: "aws_lb_listener", SrcAttr: "arn"},
		{Attr: "load_balancer_info.target_group_pair_info.target_group.name", SrcType: "aws_lb_target_group", SrcAttr: "name"},
		{Attr: "service_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "trigger_configuration.trigger_target_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_codepipeline": {
		{Attr: "artifact_store.location", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "stage.action.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_codepipeline_webhook": {
		{Attr: "target_pipeline", SrcType: "aws_codepipeline", SrcAttr: "name"},
	},
	"aws_cognito_identity_pool": {
		{Attr: "saml_provider_arns", SrcType: "aws_iam_saml_provider", SrcAttr: "arn"},
	},
	"aws_cognito_identity_pool_roles_attachment": {
		{Attr: "identity_pool_id", SrcType: "aws_cognito_identity_pool", SrcAttr: "id"},
		{Attr: "role_mapping.mapping_rule.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "roles.authenticated", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_cognito_identity_provider": {
		{Attr: "user_pool_id", SrcType: "aws_cognito_user_pool", SrcAttr: "id"},
	},
	"aws_cognito_resource_server": {
		{Attr: "user_pool_id", SrcType: "aws_cognito_user_pool", SrcAttr: "id"},
	},
	"aws_cognito_user_group": {
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "user_pool_id", SrcType: "aws_cognito_user_pool", SrcAttr: "id"},
	},
	"aws_cognito_user_pool": {
		{Attr: "lambda_config.create_auth_challenge", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "lambda_config.custom_message", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "lambda_config.define_auth_challenge", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "lambda_config.post_authentication", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "lambda_config.post_confirmation", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "lambda_config.pre_authentication", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "lambda_config.pre_sign_up", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "lambda_config.pre_token_generation", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "lambda_config.user_migration", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "lambda_config.verify_auth_challenge_response", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "sms_configuration.sns_caller_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_cognito_user_pool_client": {
		{Attr: "user_pool_id", SrcType: "aws_cognito_user_pool", SrcAttr: "id"},
	},
	"aws_cognito_user_pool_domain": {
		{Attr: "certificate_arn", SrcType: "aws_acm_certificate", SrcAttr: "arn"},
		{Attr: "user_pool_id", SrcType: "aws_cognito_user_pool", SrcAttr: "id"},
	},
	"aws_config_config_rule": {
		{Attr: "source.source_identifier", SrcType: "aws_lambda_function", SrcAttr: "arn"},
	},
	"aws_config_configuration_aggregator": {
		{Attr: "organization_aggregation_source.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_config_configuration_recorder": {
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_config_configuration_recorder_status": {
		{Attr: "name", SrcType: "aws_config_configuration_recorder", SrcAttr: "name"},
	},
	"aws_config_delivery_channel": {
		{Attr: "s3_bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "sns_topic_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_datasync_agent": {
		{Attr: "ip_address", SrcType: "aws_instance", SrcAttr: "public_ip"},
	},
	"aws_datasync_location_efs": {
		{Attr: "ec2_config.security_group_arns", SrcType: "aws_security_group", SrcAttr: "arn"},
		{Attr: "ec2_config.subnet_arn", SrcType: "aws_subnet", SrcAttr: "arn"},
		{Attr: "efs_file_system_arn", SrcType: "aws_efs_mount_target", SrcAttr: "file_system_arn"},
	},
	"aws_datasync_location_nfs": {
		{Attr: "on_prem_config.agent_arns", SrcType: "aws_datasync_agent", SrcAttr: "arn"},
		{Attr: "server_hostname", SrcType: "aws_efs_file_system", SrcAttr: "dns_name"},
	},
	"aws_datasync_location_s3": {
		{Attr: "s3_bucket_arn", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "s3_config.bucket_access_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_datasync_task": {
		{Attr: "destination_location_arn", SrcType: "aws_datasync_location_s3", SrcAttr: "arn"},
		{Attr: "source_location_arn", SrcType: "aws_datasync_location_nfs", SrcAttr: "arn"},
	},
	"aws_dax_subnet_group": {
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_db_event_subscription": {
		{Attr: "sns_topic", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_db_instance": {
		{Attr: "domain", SrcType: "aws_directory_service_directory", SrcAttr: "id"},
		{Attr: "domain_iam_role_name", SrcType: "aws_iam_role", SrcAttr: "name"},
		{Attr: "instance_class", SrcType: "aws_db_instance", SrcAttr: "instance_class"},
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "monitoring_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "option_group_name", SrcType: "aws_db_option_group", SrcAttr: "name"},
		{Attr: "parameter_group_name", SrcType: "aws_db_parameter_group", SrcAttr: "id"},
		{Attr: "replicate_source_db", SrcType: "aws_db_instance", SrcAttr: "id"},
		{Attr: "s3_import.bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "s3_import.ingestion_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "snapshot_identifier", SrcType: "aws_db_snapshot", SrcAttr: "id"},
		{Attr: "vpc_security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
	},
	"aws_db_option_group": {
		{Attr: "option.option_settings.value", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "option.vpc_security_group_memberships", SrcType: "aws_security_group", SrcAttr: "id"},
	},
	"aws_db_snapshot": {
		{Attr: "db_instance_identifier", SrcType: "aws_db_instance", SrcAttr: "id"},
	},
	"aws_db_subnet_group": {
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_default_network_acl": {
		{Attr: "default_network_acl_id", SrcType: "aws_vpc", SrcAttr: "default_network_acl_id"},
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_default_route_table": {
		{Attr: "default_route_table_id", SrcType: "aws_vpc", SrcAttr: "default_route_table_id"},
		{Attr: "route.gateway_id", SrcType: "aws_internet_gateway", SrcAttr: "id"},
		{Attr: "route.transit_gateway_id", SrcType: "aws_ec2_transit_gateway_vpc_attachment", SrcAttr: "transit_gateway_id"},
	},
	"aws_default_security_group": {
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_directory_service_conditional_forwarder": {
		{Attr: "directory_id", SrcType: "aws_directory_service_directory", SrcAttr: "id"},
	},
	"aws_directory_service_directory": {
		{Attr: "connect_settings.customer_dns_ips", SrcType: "aws_directory_service_directory", SrcAttr: "dns_ip_addresses"},
		{Attr: "connect_settings.subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "connect_settings.vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
		{Attr: "vpc_settings.subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "vpc_settings.vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_dms_endpoint": {
		{Attr: "s3_settings.service_access_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "service_access_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_dms_replication_instance": {
		{Attr: "kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "vpc_security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
	},
	"aws_dms_replication_subnet_group": {
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_dms_replication_task": {
		{Attr: "replication_instance_arn", SrcType: "aws_dms_replication_instance", SrcAttr: "replication_instance_arn"},
		{Attr: "source_endpoint_arn", SrcType: "aws_dms_endpoint", SrcAttr: "endpoint_arn"},
		{Attr: "target_endpoint_arn", SrcType: "aws_dms_endpoint", SrcAttr: "endpoint_arn"},
	},
	"aws_dx_bgp_peer": {
		{Attr: "virtual_interface_id", SrcType: "aws_dx_private_virtual_interface", SrcAttr: "id"},
	},
	"aws_dx_connection_association": {
		{Attr: "connection_id", SrcType: "aws_dx_connection", SrcAttr: "id"},
		{Attr: "lag_id", SrcType: "aws_dx_lag", SrcAttr: "id"},
	},
	"aws_dx_gateway_association": {
		{Attr: "dx_gateway_id", SrcType: "aws_dx_gateway", SrcAttr: "id"},
	},
	"aws_dx_hosted_private_virtual_interface_accepter": {
		{Attr: "virtual_interface_id", SrcType: "aws_dx_hosted_private_virtual_interface", SrcAttr: "id"},
		{Attr: "vpn_gateway_id", SrcType: "aws_vpn_gateway", SrcAttr: "id"},
	},
	"aws_dx_hosted_public_virtual_interface_accepter": {
		{Attr: "virtual_interface_id", SrcType: "aws_dx_hosted_public_virtual_interface", SrcAttr: "id"},
	},
	"aws_dx_private_virtual_interface": {
		{Attr: "dx_gateway_id", SrcType: "aws_dx_gateway", SrcAttr: "id"},
		{Attr: "vpn_gateway_id", SrcType: "aws_vpn_gateway", SrcAttr: "id"},
	},
	"aws_dynamodb_table_item": {
		{Attr: "hash_key", SrcType: "aws_dynamodb_table", SrcAttr: "hash_key"},
		{Attr: "range_key", SrcType: "aws_dynamodb_table", SrcAttr: "range_key"},
		{Attr: "table_name", SrcType: "aws_dynamodb_table", SrcAttr: "name"},
	},
	"aws_ebs_snapshot_copy": {
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "source_snapshot_id", SrcType: "aws_ebs_snapshot", SrcAttr: "id"},
	},
	"aws_ebs_volume": {
		{Attr: "availability_zone", SrcType: "aws_instance", SrcAttr: "availability_zone"},
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
	},
	"aws_ec2_fleet": {
		{Attr: "launch_template_config.launch_template_specification.launch_template_id", SrcType: "aws_launch_template", SrcAttr: "id"},
		{Attr: "launch_template_config.launch_template_specification.version", SrcType: "aws_launch_template", SrcAttr: "latest_version"},
		{Attr: "launch_template_config.override.instance_type", SrcType: "aws_launch_template", SrcAttr: "instance_type"},
	},
	"aws_ec2_transit_gateway_route": {
		{Attr: "transit_gateway_attachment_id", SrcType: "aws_ec2_transit_gateway_vpc_attachment", SrcAttr: "id"},
		{Attr: "transit_gateway_route_table_id", SrcType: "aws_ec2_transit_gateway", SrcAttr: "association_default_route_table_id"},
	},
	"aws_ec2_transit_gateway_route_table": {
		{Attr: "transit_gateway_id", SrcType: "aws_ec2_transit_gateway", SrcAttr: "id"},
	},
	"aws_ec2_transit_gateway_route_table_association": {
		{Attr: "transit_gateway_attachment_id", SrcType: "aws_ec2_transit_gateway_vpc_attachment", SrcAttr: "id"},
		{Attr: "transit_gateway_route_table_id", SrcType: "aws_ec2_transit_gateway_route_table", SrcAttr: "id"},
	},
	"aws_ec2_transit_gateway_route_table_propagation": {
		{Attr: "transit_gateway_attachment_id", SrcType: "aws_ec2_transit_gateway_vpc_attachment", SrcAttr: "id"},
		{Attr: "transit_gateway_route_table_id", SrcType: "aws_ec2_transit_gateway_route_table", SrcAttr: "id"},
	},
	"aws_ec2_transit_gateway_vpc_attachment": {
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "transit_gateway_id", SrcType: "aws_ec2_transit_gateway", SrcAttr: "id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_ecr_lifecycle_policy": {
		{Attr: "repository", SrcType: "aws_ecr_repository", SrcAttr: "name"},
	},
	"aws_ecr_repository_policy": {
		{Attr: "repository", SrcType: "aws_ecr_repository", SrcAttr: "name"},
	},
	"aws_ecs_service": {
		{Attr: "load_balancer.elb_name", SrcType: "aws_elb", SrcAttr: "id"},
		{Attr: "network_configuration.security_groups", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "network_configuration.subnets", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "service_registries.registry_arn", SrcType: "aws_service_discovery_service", SrcAttr: "arn"},
	},
	"aws_ecs_task_definition": {
		{Attr: "execution_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "task_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_efs_file_system": {
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
	},
	"aws_efs_mount_target": {
		{Attr: "file_system_id", SrcType: "aws_efs_file_system", SrcAttr: "id"},
		{Attr: "security_groups", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_egress_only_internet_gateway": {
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_eip": {
		{Attr: "network_interface", SrcType: "aws_network_interface", SrcAttr: "id"},
	},
	"aws_eip_association": {
		{Attr: "allocation_id", SrcType: "aws_eip", SrcAttr: "id"},
		{Attr: "network_interface_id", SrcType: "aws_network_interface", SrcAttr: "id"},
		{Attr: "public_ip", SrcType: "aws_eip", SrcAttr: "public_ip"},
	},
	"aws_eks_cluster": {
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "vpc_config.security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "vpc_config.subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_elastic_beanstalk_application": {
		{Attr: "appversion_lifecycle.service_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_elastic_beanstalk_application_version": {
		{Attr: "application", SrcType: "aws_elastic_beanstalk_application", SrcAttr: "name"},
		{Attr: "bucket", SrcType: "aws_s3_bucket", SrcAttr: "id"},
		{Attr: "key", SrcType: "aws_s3_bucket_object", SrcAttr: "id"},
	},
	"aws_elastic_beanstalk_configuration_template": {
		{Attr: "application", SrcType: "aws_elastic_beanstalk_application", SrcAttr: "name"},
	},
	"aws_elastic_beanstalk_environment": {
		{Attr: "application", SrcType: "aws_elastic_beanstalk_application", SrcAttr: "name"},
		{Attr: "template_name", SrcType: "aws_elastic_beanstalk_configuration_template", SrcAttr: "name"},
		{Attr: "version_label", SrcType: "aws_elastic_beanstalk_application_version", SrcAttr: "name"},
	},
	"aws_elasticache_cluster": {
		{Attr: "notification_topic_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
		{Attr: "replication_group_id", SrcType: "aws_elasticache_replication_group", SrcAttr: "id"},
		{Attr: "security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "security_group_names", SrcType: "aws_elasticache_security_group", SrcAttr: "name"},
		{Attr: "subnet_group_name", SrcType: "aws_elasticache_subnet_group", SrcAttr: "name"},
	},
	"aws_elasticache_replication_group": {
		{Attr: "security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "security_group_names", SrcType: "aws_elasticache_security_group", SrcAttr: "name"},
		{Attr: "subnet_group_name", SrcType: "aws_elasticache_subnet_group", SrcAttr: "name"},
	},
	"aws_elasticache_security_group": {
		{Attr: "security_group_names", SrcType: "aws_security_group", SrcAttr: "name"},
	},
	"aws_elasticache_subnet_group": {
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_elasticsearch_domain": {
		{Attr: "encrypt_at_rest.kms_key_id", SrcType: "aws_kms_key", SrcAttr: "key_id"},
		{Attr: "log_publishing_options.cloudwatch_log_group_arn", SrcType: "aws_cloudwatch_log_group", SrcAttr: "arn"},
		{Attr: "vpc_options.security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "vpc_options.subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_elasticsearch_domain_policy": {
		{Attr: "domain_name", SrcType: "aws_elasticsearch_domain", SrcAttr: "domain_name"},
	},
	"aws_elastictranscoder_pipeline": {
		{Attr: "aws_kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "content_config.bucket", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "input_bucket", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "notifications.completed", SrcType: "aws_sns_topic", SrcAttr: "arn"},
		{Attr: "notifications.warning", SrcType: "aws_sns_topic", SrcAttr: "arn"},
		{Attr: "output_bucket", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "thumbnail_config.bucket", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
	},
	"aws_elb": {
		{Attr: "access_logs.bucket", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "availability_zones", SrcType: "aws_instance", SrcAttr: "availability_zone"},
		{Attr: "instances", SrcType: "aws_instance", SrcAttr: "id"},
		{Attr: "listener.ssl_certificate_id", SrcType: "aws_iam_server_certificate", SrcAttr: "arn"},
		{Attr: "security_groups", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "subnets", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_elb_attachment": {
		{Attr: "elb", SrcType: "aws_elb", SrcAttr: "id"},
		{Attr: "instance", SrcType: "aws_instance", SrcAttr: "id"},
	},
	"aws_emr_cluster": {
		{Attr: "autoscaling_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "ec2_attributes.emr_managed_master_security_group", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "ec2_attributes.emr_managed_slave_security_group", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "ec2_attributes.instance_profile", SrcType: "aws_iam_instance_profile", SrcAttr: "arn"},
		{Attr: "ec2_attributes.subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "security_configuration", SrcType: "aws_emr_security_configuration", SrcAttr: "name"},
		{Attr: "service_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_emr_instance_group": {
		{Attr: "cluster_id", SrcType: "aws_emr_cluster", SrcAttr: "id"},
	},
	"aws_flow_log": {
		{Attr: "iam_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "log_group_name", SrcType: "aws_cloudwatch_log_group", SrcAttr: "name"},
		{Attr: "subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_gamelift_alias": {
		{Attr: "routing_strategy.fleet_id", SrcType: "aws_gamelift_fleet", SrcAttr: "id"},
	},
	"aws_gamelift_build": {
		{Attr: "storage_location.bucket", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "storage_location.key", SrcType: "aws_s3_bucket_object", SrcAttr: "key"},
		{Attr: "storage_location.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_gamelift_fleet": {
		{Attr: "build_id", SrcType: "aws_gamelift_build", SrcAttr: "id"},
	},
	"aws_gamelift_game_session_queue": {
		{Attr: "destinations", SrcType: "aws_gamelift_fleet", SrcAttr: "arn"},
	},
	"aws_glacier_vault": {
		{Attr: "notification.sns_topic", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_glacier_vault_lock": {
		{Attr: "vault_name", SrcType: "aws_glacier_vault", SrcAttr: "name"},
	},
	"aws_glue_catalog_table": {
		{Attr: "database_name", SrcType: "aws_glue_catalog_database", SrcAttr: "name"},
	},
	"aws_glue_connection": {
		{Attr: "connection_properties.PASSWORD", SrcType: "aws_rds_cluster", SrcAttr: "master_password"},
		{Attr: "connection_properties.USERNAME", SrcType: "aws_rds_cluster", SrcAttr: "master_username"},
		{Attr: "physical_connection_requirements.availability_zone", SrcType: "aws_subnet", SrcAttr: "availability_zone"},
		{Attr: "physical_connection_requirements.security_group_id_list", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "physical_connection_requirements.subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_glue_crawler": {
		{Attr: "classifiers", SrcType: "aws_glue_classifier", SrcAttr: "id"},
		{Attr: "database_name", SrcType: "aws_glue_catalog_database", SrcAttr: "name"},
		{Attr: "jdbc_target.connection_name", SrcType: "aws_glue_connection", SrcAttr: "name"},
		{Attr: "security_configuration", SrcType: "aws_glue_security_configuration", SrcAttr: "name"},
	},
	"aws_glue_job": {
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_glue_security_configuration": {
		{Attr: "encryption_configuration.cloudwatch_encryption.kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "encryption_configuration.job_bookmarks_encryption.kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "encryption_configuration.s3_encryption.kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
	},
	"aws_glue_trigger": {
		{Attr: "actions.job_name", SrcType: "aws_glue_job", SrcAttr: "name"},
		{Attr: "predicate.conditions.job_name", SrcType: "aws_glue_job", SrcAttr: "name"},
	},
	"aws_guardduty_ipset": {
		{Attr: "detector_id", SrcType: "aws_guardduty_detector", SrcAttr: "id"},
	},
	"aws_guardduty_member": {
		{Attr: "account_id", SrcType: "aws_guardduty_detector", SrcAttr: "account_id"},
		{Attr: "detector_id", SrcType: "aws_guardduty_detector", SrcAttr: "id"},
	},
	"aws_guardduty_threatintelset": {
		{Attr: "detector_id", SrcType: "aws_guardduty_detector", SrcAttr: "id"},
	},
	"aws_iam_access_key": {
		{Attr: "user", SrcType: "aws_iam_user", SrcAttr: "name"},
	},
	"aws_iam_group_membership": {
		{Attr: "group", SrcType: "aws_iam_group", SrcAttr: "name"},
		{Attr: "users", SrcType: "aws_iam_user", SrcAttr: "name"},
	},
	"aws_iam_group_policy": {
		{Attr: "group", SrcType: "aws_iam_group", SrcAttr: "id"},
	},
	"aws_iam_group_policy_attachment": {
		{Attr: "group", SrcType: "aws_iam_group", SrcAttr: "name"},
		{Attr: "policy_arn", SrcType: "aws_iam_policy", SrcAttr: "arn"},
	},
	"aws_iam_instance_profile": {
		{Attr: "role", SrcType: "aws_iam_role", SrcAttr: "name"},
		{Attr: "roles", SrcType: "aws_iam_role", SrcAttr: "name"},
	},
	"aws_iam_policy_attachment": {
		{Attr: "groups", SrcType: "aws_iam_group", SrcAttr: "name"},
		{Attr: "policy_arn", SrcType: "aws_iam_policy", SrcAttr: "arn"},
		{Attr: "roles", SrcType: "aws_iam_role", SrcAttr: "name"},
		{Attr: "users", SrcType: "aws_iam_user", SrcAttr: "name"},
	},
	"aws_iam_role_policy_attachment": {
		{Attr: "policy_arn", SrcType: "aws_iam_policy", SrcAttr: "arn"},
	},
	"aws_iam_server_certificate": {
		{Attr: "certificate_body", SrcType: "tls_self_signed_cert", SrcAttr: "cert_pem"},
		{Attr: "private_key", SrcType: "tls_private_key", SrcAttr: "private_key_pem"},
	},
	"aws_iam_user_group_membership": {
		{Attr: "groups", SrcType: "aws_iam_group", SrcAttr: "name"},
		{Attr: "user", SrcType: "aws_iam_user", SrcAttr: "name"},
	},
	"aws_iam_user_login_profile": {
		{Attr: "user", SrcType: "aws_iam_user", SrcAttr: "name"},
	},
	"aws_iam_user_policy": {
		{Attr: "user", SrcType: "aws_iam_user", SrcAttr: "name"},
	},
	"aws_iam_user_policy_attachment": {
		{Attr: "policy_arn", SrcType: "aws_iam_policy", SrcAttr: "arn"},
		{Attr: "user", SrcType: "aws_iam_user", SrcAttr: "name"},
	},
	"aws_iam_user_ssh_key": {
		{Attr: "username", SrcType: "aws_iam_user", SrcAttr: "name"},
	},
	"aws_inspector_assessment_target": {
		{Attr: "resource_group_arn", SrcType: "aws_inspector_resource_group", SrcAttr: "arn"},
	},
	"aws_inspector_assessment_template": {
		{Attr: "target_arn", SrcType: "aws_inspector_assessment_target", SrcAttr: "arn"},
	},
	"aws_instance": {
		{Attr: "availability_zone", SrcType: "aws_subnet", SrcAttr: "availability_zone"},
		{Attr: "iam_instance_profile", SrcType: "aws_iam_instance_profile", SrcAttr: "name"},
		{Attr: "network_interface.network_interface_id", SrcType: "aws_network_interface", SrcAttr: "id"},
		{Attr: "placement_group", SrcType: "aws_placement_group", SrcAttr: "name"},
		{Attr: "security_groups", SrcType: "aws_security_group", SrcAttr: "name"},
		{Attr: "vpc_security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
	},
	"aws_internet_gateway": {
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_iot_policy_attachment": {
		{Attr: "policy", SrcType: "aws_iot_policy", SrcAttr: "name"},
		{Attr: "target", SrcType: "aws_iot_certificate", SrcAttr: "arn"},
	},
	"aws_iot_thing": {
		{Attr: "thing_type_name", SrcType: "aws_iot_thing_type", SrcAttr: "name"},
	},
	"aws_iot_thing_attachment": {
		{Attr: "principal", SrcType: "aws_iot_certificate", SrcAttr: "arn"},
		{Attr: "thing", SrcType: "aws_iot_thing", SrcAttr: "name"},
	},
	"aws_iot_thing_principal_attachment": {
		{Attr: "principal", SrcType: "aws_iot_certificate", SrcAttr: "arn"},
		{Attr: "thing", SrcType: "aws_iot_thing", SrcAttr: "name"},
	},
	"aws_iot_topic_rule": {
		{Attr: "cloudwatch_alarm.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "cloudwatch_metric.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "dynamodb.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "elasticsearch.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "firehose.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "kinesis.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "republish.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "s3.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "sns.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "sqs.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_kinesis_analytics_application": {
		{Attr: "cloudwatch_logging_options.log_stream_arn", SrcType: "aws_cloudwatch_log_stream", SrcAttr: "arn"},
		{Attr: "cloudwatch_logging_options.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "inputs.kinesis_stream.resource_arn", SrcType: "aws_kinesis_stream", SrcAttr: "arn"},
		{Attr: "inputs.kinesis_stream.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "outputs.kinesis_stream.resource_arn", SrcType: "aws_kinesis_stream", SrcAttr: "arn"},
		{Attr: "outputs.kinesis_stream.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "reference_data_sources.s3.bucket_arn", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "reference_data_sources.s3.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_kinesis_firehose_delivery_stream": {
		{Attr: "elasticsearch_configuration.domain_arn", SrcType: "aws_elasticsearch_domain", SrcAttr: "arn"},
		{Attr: "elasticsearch_configuration.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "extended_s3_configuration.bucket_arn", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "extended_s3_configuration.data_format_conversion_configuration.schema_configuration.database_name", SrcType: "aws_glue_catalog_table", SrcAttr: "database_name"},
		{Attr: "extended_s3_configuration.data_format_conversion_configuration.schema_configuration.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "extended_s3_configuration.data_format_conversion_configuration.schema_configuration.table_name", SrcType: "aws_glue_catalog_table", SrcAttr: "name"},
		{Attr: "extended_s3_configuration.kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "extended_s3_configuration.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "extended_s3_configuration.s3_backup_configuration.bucket_arn", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "extended_s3_configuration.s3_backup_configuration.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "kinesis_source_configuration.kinesis_stream_arn", SrcType: "aws_kinesis_stream", SrcAttr: "arn"},
		{Attr: "kinesis_source_configuration.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "redshift_configuration.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "redshift_configuration.s3_backup_configuration.bucket_arn", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "redshift_configuration.s3_backup_configuration.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "s3_configuration.bucket_arn", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "s3_configuration.cloudwatch_logging_options.log_group_name", SrcType: "aws_cloudwatch_log_group", SrcAttr: "name"},
		{Attr: "s3_configuration.cloudwatch_logging_options.log_stream_name", SrcType: "aws_cloudwatch_log_stream", SrcAttr: "name"},
		{Attr: "s3_configuration.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_kinesis_stream": {
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "id"},
	},
	"aws_kms_grant": {
		{Attr: "grantee_principal", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "retiring_principal", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_lambda_event_source_mapping": {
		{Attr: "function_name", SrcType: "aws_lambda_function", SrcAttr: "arn"},
	},
	"aws_lambda_function": {
		{Attr: "dead_letter_config.target_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
		{Attr: "kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "s3_object_version", SrcType: "aws_s3_bucket_object", SrcAttr: "version_id"},
		{Attr: "vpc_config.security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "vpc_config.subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_lambda_permission": {
		{Attr: "principal", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "qualifier", SrcType: "aws_lambda_alias", SrcAttr: "name"},
	},
	"aws_launch_configuration": {
		{Attr: "iam_instance_profile", SrcType: "aws_iam_instance_profile", SrcAttr: "name"},
		{Attr: "security_groups", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "vpc_classic_link_id", SrcType: "aws_vpc", SrcAttr: "id"},
		{Attr: "vpc_classic_link_security_groups", SrcType: "aws_security_group", SrcAttr: "id"},
	},
	"aws_launch_template": {
		{Attr: "capacity_reservation_specification.capacity_reservation_target.capacity_reservation_id", SrcType: "aws_ec2_capacity_reservation", SrcAttr: "id"},
		{Attr: "iam_instance_profile.name", SrcType: "aws_iam_instance_profile", SrcAttr: "id"},
		{Attr: "network_interfaces.network_interface_id", SrcType: "aws_network_interface", SrcAttr: "id"},
	},
	"aws_lb": {
		{Attr: "access_logs.bucket", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "security_groups", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "subnet_mapping.allocation_id", SrcType: "aws_eip", SrcAttr: "id"},
		{Attr: "subnet_mapping.subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "subnets", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_lb_cookie_stickiness_policy": {
		{Attr: "load_balancer", SrcType: "aws_elb", SrcAttr: "id"},
	},
	"aws_lb_listener": {
		{Attr: "action.target_group_arn", SrcType: "aws_lb_target_group", SrcAttr: "arn"},
		{Attr: "default_action.authenticate_cognito.user_pool_arn", SrcType: "aws_cognito_user_pool", SrcAttr: "arn"},
		{Attr: "default_action.authenticate_cognito.user_pool_client_id", SrcType: "aws_cognito_user_pool_client", SrcAttr: "id"},
		{Attr: "default_action.authenticate_cognito.user_pool_domain", SrcType: "aws_cognito_user_pool_domain", SrcAttr: "domain"},
		{Attr: "listener_arn", SrcType: "aws_lb_listener", SrcAttr: "arn"},
	},
	"aws_lb_listener_certificate": {
		{Attr: "listener_arn", SrcType: "aws_lb_listener", SrcAttr: "arn"},
	},
	"aws_lb_listener_rule": {
		{Attr: "action.authenticate_cognito.user_pool_arn", SrcType: "aws_cognito_user_pool", SrcAttr: "arn"},
		{Attr: "action.authenticate_cognito.user_pool_client_id", SrcType: "aws_cognito_user_pool_client", SrcAttr: "id"},
		{Attr: "action.authenticate_cognito.user_pool_domain", SrcType: "aws_cognito_user_pool_domain", SrcAttr: "domain"},
		{Attr: "action.target_group_arn", SrcType: "aws_lb_target_group", SrcAttr: "arn"},
		{Attr: "listener_arn", SrcType: "aws_lb_listener", SrcAttr: "arn"},
	},
	"aws_lb_ssl_negotiation_policy": {
		{Attr: "load_balancer", SrcType: "aws_elb", SrcAttr: "id"},
	},
	"aws_lb_target_group": {
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_lb_target_group_attachment": {
		{Attr: "availability_zone", SrcType: "aws_instance", SrcAttr: "availability_zone"},
		{Attr: "target_group_arn", SrcType: "aws_lb_target_group", SrcAttr: "arn"},
	},
	"aws_lightsail_instance": {
		{Attr: "key_pair_name", SrcType: "aws_lightsail_key_pair", SrcAttr: "name"},
	},
	"aws_lightsail_static_ip_attachment": {
		{Attr: "instance_name", SrcType: "aws_lightsail_instance", SrcAttr: "name"},
		{Attr: "static_ip_name", SrcType: "aws_lightsail_static_ip", SrcAttr: "name"},
	},
	"aws_load_balancer_backend_server_policy": {
		{Attr: "load_balancer_name", SrcType: "aws_elb", SrcAttr: "name"},
		{Attr: "policy_names", SrcType: "aws_load_balancer_policy", SrcAttr: "policy_name"},
	},
	"aws_load_balancer_listener_policy": {
		{Attr: "load_balancer_name", SrcType: "aws_elb", SrcAttr: "name"},
		{Attr: "policy_names", SrcType: "aws_load_balancer_policy", SrcAttr: "policy_name"},
	},
	"aws_load_balancer_policy": {
		{Attr: "load_balancer_name", SrcType: "aws_elb", SrcAttr: "name"},
	},
	"aws_macie_s3_bucket_association": {
		{Attr: "bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "id"},
	},
	"aws_main_route_table_association": {
		{Attr: "route_table_id", SrcType: "aws_route_table", SrcAttr: "id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_media_store_container_policy": {
		{Attr: "container_name", SrcType: "aws_media_store_container", SrcAttr: "name"},
	},
	"aws_mq_broker": {
		{Attr: "configuration.id", SrcType: "aws_mq_configuration", SrcAttr: "id"},
		{Attr: "configuration.revision", SrcType: "aws_mq_configuration", SrcAttr: "latest_revision"},
		{Attr: "security_groups", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_nat_gateway": {
		{Attr: "subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_neptune_cluster": {
		{Attr: "iam_roles", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "neptune_subnet_group_name", SrcType: "aws_neptune_subnet_group", SrcAttr: "name"},
	},
	"aws_neptune_cluster_instance": {
		{Attr: "cluster_identifier", SrcType: "aws_neptune_cluster", SrcAttr: "id"},
		{Attr: "neptune_parameter_group_name", SrcType: "aws_neptune_parameter_group", SrcAttr: "name"},
	},
	"aws_neptune_cluster_snapshot": {
		{Attr: "db_cluster_identifier", SrcType: "aws_neptune_cluster", SrcAttr: "id"},
	},
	"aws_neptune_event_subscription": {
		{Attr: "sns_topic_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_neptune_subnet_group": {
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_network_acl": {
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_network_acl_rule": {
		{Attr: "network_acl_id", SrcType: "aws_network_acl", SrcAttr: "id"},
	},
	"aws_network_interface": {
		{Attr: "attachment.instance", SrcType: "aws_instance", SrcAttr: "id"},
		{Attr: "subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "tags.Name", SrcType: "aws_vpc", SrcAttr: "tags.Name"},
	},
	"aws_network_interface_attachment": {
		{Attr: "instance_id", SrcType: "aws_instance", SrcAttr: "id"},
		{Attr: "network_interface_id", SrcType: "aws_network_interface", SrcAttr: "id"},
	},
	"aws_opsworks_application": {
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_custom_layer": {
		{Attr: "custom_security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_ganglia_layer": {
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_haproxy_layer": {
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_instance": {
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_java_app_layer": {
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_memcached_layer": {
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_mysql_layer": {
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_nodejs_app_layer": {
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_permission": {
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_php_app_layer": {
		{Attr: "custom_security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_rails_app_layer": {
		{Attr: "custom_security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_rds_db_instance": {
		{Attr: "rds_db_instance_arn", SrcType: "aws_db_instance", SrcAttr: "arn"},
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_stack": {
		{Attr: "default_instance_profile_arn", SrcType: "aws_iam_instance_profile", SrcAttr: "arn"},
		{Attr: "default_subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "service_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_opsworks_static_web_layer": {
		{Attr: "custom_security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "stack_id", SrcType: "aws_opsworks_stack", SrcAttr: "id"},
	},
	"aws_opsworks_user_profile": {
		{Attr: "ssh_username", SrcType: "aws_iam_user", SrcAttr: "name"},
		{Attr: "user_arn", SrcType: "aws_iam_user", SrcAttr: "arn"},
	},
	"aws_organizations_policy_attachment": {
		{Attr: "policy_id", SrcType: "aws_organizations_policy", SrcAttr: "id"},
	},
	"aws_pinpoint_adm_channel": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
	},
	"aws_pinpoint_apns_channel": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
	},
	"aws_pinpoint_apns_sandbox_channel": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
	},
	"aws_pinpoint_apns_voip_channel": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
	},
	"aws_pinpoint_apns_voip_sandbox_channel": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
	},
	"aws_pinpoint_app": {
		{Attr: "campaign_hook.lambda_function_name", SrcType: "aws_lambda_function", SrcAttr: "arn"},
	},
	"aws_pinpoint_baidu_channel": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
	},
	"aws_pinpoint_email_channel": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
		{Attr: "identity", SrcType: "aws_ses_domain_identity", SrcAttr: "arn"},
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_pinpoint_event_stream": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
		{Attr: "destination_stream_arn", SrcType: "aws_kinesis_stream", SrcAttr: "arn"},
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_pinpoint_gcm_channel": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
	},
	"aws_pinpoint_sms_channel": {
		{Attr: "application_id", SrcType: "aws_pinpoint_app", SrcAttr: "application_id"},
	},
	"aws_proxy_protocol_policy": {
		{Attr: "load_balancer", SrcType: "aws_elb", SrcAttr: "name"},
	},
	"aws_rds_cluster": {
		{Attr: "db_cluster_parameter_group_name", SrcType: "aws_rds_cluster_parameter_group", SrcAttr: "name"},
		{Attr: "db_subnet_group_name", SrcType: "aws_db_subnet_group", SrcAttr: "name"},
		{Attr: "iam_roles", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "s3_import.bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "s3_import.ingestion_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "snapshot_identifier", SrcType: "aws_db_cluster_snapshot", SrcAttr: "id"},
		{Attr: "vpc_security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
	},
	"aws_rds_cluster_endpoint": {
		{Attr: "cluster_identifier", SrcType: "aws_rds_cluster", SrcAttr: "id"},
		{Attr: "excluded_members", SrcType: "aws_rds_cluster_instance", SrcAttr: "id"},
		{Attr: "static_members", SrcType: "aws_rds_cluster_instance", SrcAttr: "id"},
	},
	"aws_rds_cluster_instance": {
		{Attr: "db_parameter_group_name", SrcType: "aws_db_parameter_group", SrcAttr: "name"},
		{Attr: "engine", SrcType: "aws_rds_cluster", SrcAttr: "engine"},
		{Attr: "monitoring_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "performance_insights_kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
	},
	"aws_redshift_cluster": {
		{Attr: "bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "id"},
		{Attr: "cluster_subnet_group_name", SrcType: "aws_redshift_subnet_group", SrcAttr: "name"},
		{Attr: "iam_roles", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "snapshot_copy.grant_name", SrcType: "aws_redshift_snapshot_copy_grant", SrcAttr: "snapshot_copy_grant_name"},
		{Attr: "vpc_security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
	},
	"aws_redshift_event_subscription": {
		{Attr: "sns_topic", SrcType: "aws_sns_topic", SrcAttr: "arn"},
		{Attr: "sns_topic_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_redshift_subnet_group": {
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
	},
	"aws_route": {
		{Attr: "destination_ipv6_cidr_block", SrcType: "aws_vpc", SrcAttr: "ipv6_cidr_block"},
		{Attr: "egress_only_gateway_id", SrcType: "aws_egress_only_internet_gateway", SrcAttr: "id"},
		{Attr: "gateway_id", SrcType: "aws_internet_gateway", SrcAttr: "id"},
		{Attr: "instance_id", SrcType: "aws_instance", SrcAttr: "id"},
		{Attr: "network_interface_id", SrcType: "aws_network_interface", SrcAttr: "id"},
		{Attr: "transit_gateway_id", SrcType: "aws_ec2_transit_gateway_vpc_attachment", SrcAttr: "transit_gateway_id"},
		{Attr: "vpc_peering_connection_id", SrcType: "aws_vpc_peering_connection", SrcAttr: "id"},
	},
	"aws_route53_health_check": {
		{Attr: "child_healthchecks", SrcType: "aws_route53_health_check", SrcAttr: "id"},
		{Attr: "cloudwatch_alarm_name", SrcType: "aws_cloudwatch_metric_alarm", SrcAttr: "alarm_name"},
	},
	"aws_route53_query_log": {
		{Attr: "cloudwatch_log_group_arn", SrcType: "aws_cloudwatch_log_group", SrcAttr: "arn"},
		{Attr: "zone_id", SrcType: "aws_route53_zone", SrcAttr: "zone_id"},
	},
	"aws_route53_record": {
		{Attr: "health_check_id", SrcType: "aws_route53_health_check", SrcAttr: "id"},
	},
	"aws_route53_zone": {
		{Attr: "delegation_set_id", SrcType: "aws_route53_delegation_set", SrcAttr: "id"},
		{Attr: "vpc.vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_route53_zone_association": {
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_route_table": {
		{Attr: "propagating_vgws", SrcType: "aws_vpn_gateway", SrcAttr: "id"},
		{Attr: "route.egress_only_gateway_id", SrcType: "aws_egress_only_internet_gateway", SrcAttr: "id"},
		{Attr: "route.gateway_id", SrcType: "aws_internet_gateway", SrcAttr: "id"},
		{Attr: "route.instance_id", SrcType: "aws_instance", SrcAttr: "id"},
		{Attr: "route.nat_gateway_id", SrcType: "aws_nat_gateway", SrcAttr: "id"},
		{Attr: "route.transit_gateway_id", SrcType: "aws_ec2_transit_gateway_vpc_attachment", SrcAttr: "transit_gateway_id"},
		{Attr: "route.vpc_peering_connection_id", SrcType: "aws_vpc_peering_connection", SrcAttr: "id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_route_table_association": {
		{Attr: "route_table_id", SrcType: "aws_route_table", SrcAttr: "id"},
	},
	"aws_s3_bucket": {
		{Attr: "logging.target_bucket", SrcType: "aws_s3_bucket", SrcAttr: "id"},
		{Attr: "replication_configuration.role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "replication_configuration.rules.destination.bucket", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "replication_configuration.rules.destination.replica_kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "server_side_encryption_configuration.rule.apply_server_side_encryption_by_default.kms_master_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
	},
	"aws_s3_bucket_inventory": {
		{Attr: "bucket", SrcType: "aws_s3_bucket", SrcAttr: "id"},
		{Attr: "destination.bucket.bucket_arn", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "destination.bucket.encryption.sse_kms.key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
	},
	"aws_s3_bucket_notification": {
		{Attr: "bucket", SrcType: "aws_s3_bucket", SrcAttr: "id"},
		{Attr: "lambda_function.lambda_function_arn", SrcType: "aws_lambda_function", SrcAttr: "arn"},
		{Attr: "queue.queue_arn", SrcType: "aws_sqs_queue", SrcAttr: "arn"},
		{Attr: "topic.topic_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_s3_bucket_object": {
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "arn"},
	},
	"aws_secretsmanager_secret": {
		{Attr: "kms_key_id", SrcType: "aws_kms_key", SrcAttr: "id"},
		{Attr: "rotation_lambda_arn", SrcType: "aws_lambda_function", SrcAttr: "arn"},
	},
	"aws_secretsmanager_secret_version": {
		{Attr: "secret_id", SrcType: "aws_secretsmanager_secret", SrcAttr: "id"},
	},
	"aws_security_group": {
		{Attr: "egress.prefix_list_ids", SrcType: "aws_vpc_endpoint", SrcAttr: "prefix_list_id"},
		{Attr: "egress.security_groups", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "ingress.prefix_list_ids", SrcType: "aws_vpc_endpoint", SrcAttr: "prefix_list_id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_security_group_rule": {
		{Attr: "prefix_list_ids", SrcType: "aws_vpc_endpoint", SrcAttr: "prefix_list_id"},
		{Attr: "security_group_id", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "source_security_group_id", SrcType: "aws_security_group", SrcAttr: "id"},
	},
	"aws_service_discovery_private_dns_namespace": {
		{Attr: "vpc", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_ses_active_receipt_rule_set": {
		{Attr: "rule_set_name", SrcType: "aws_ses_receipt_rule_set", SrcAttr: "rule_set_name"},
	},
	"aws_ses_domain_dkim": {
		{Attr: "domain", SrcType: "aws_ses_domain_identity", SrcAttr: "domain"},
	},
	"aws_ses_domain_identity_verification": {
		{Attr: "domain", SrcType: "aws_ses_domain_identity", SrcAttr: "id"},
	},
	"aws_ses_domain_mail_from": {
		{Attr: "domain", SrcType: "aws_ses_domain_identity", SrcAttr: "domain"},
	},
	"aws_ses_event_destination": {
		{Attr: "configuration_set_name", SrcType: "aws_ses_configuration_set", SrcAttr: "name"},
		{Attr: "kinesis_destination.role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "kinesis_destination.stream_arn", SrcType: "aws_kinesis_firehose_delivery_stream", SrcAttr: "arn"},
		{Attr: "sns_destination.topic_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_ses_identity_notification_topic": {
		{Attr: "topic_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_ses_receipt_rule": {
		{Attr: "after", SrcType: "aws_ses_receipt_rule", SrcAttr: "name"},
		{Attr: "rule_set_name", SrcType: "aws_ses_receipt_rule_set", SrcAttr: "rule_set_name"},
		{Attr: "s3_action.bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "id"},
	},
	"aws_sfn_state_machine": {
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_snapshot_create_volume_permission": {
		{Attr: "snapshot_id", SrcType: "aws_ebs_snapshot", SrcAttr: "id"},
	},
	"aws_sns_sms_preferences": {
		{Attr: "delivery_status_iam_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_sns_topic": {
		{Attr: "application_failure_feedback_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "application_success_feedback_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "http_failure_feedback_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "http_success_feedback_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "lambda_failure_feedback_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "lambda_success_feedback_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "sqs_failure_feedback_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "sqs_success_feedback_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_sns_topic_policy": {
		{Attr: "arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_sns_topic_subscription": {
		{Attr: "topic_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
	},
	"aws_spot_datafeed_subscription": {
		{Attr: "bucket", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
	},
	"aws_spot_fleet_request": {
		{Attr: "iam_fleet_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "launch_specification.iam_instance_profile_arn", SrcType: "aws_iam_instance_profile", SrcAttr: "arn"},
		{Attr: "launch_specification.key_name", SrcType: "aws_key_pair", SrcAttr: "key_name"},
		{Attr: "launch_specification.subnet_id", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "load_balancers", SrcType: "aws_elb", SrcAttr: "name"},
		{Attr: "target_group_arns", SrcType: "aws_alb_target_group", SrcAttr: "arn"},
	},
	"aws_sqs_queue_policy": {
		{Attr: "queue_url", SrcType: "aws_sqs_queue", SrcAttr: "id"},
	},
	"aws_ssm_association": {
		{Attr: "document_version", SrcType: "aws_ssm_document", SrcAttr: "latest_version"},
		{Attr: "instance_id", SrcType: "aws_instance", SrcAttr: "id"},
		{Attr: "name", SrcType: "aws_ssm_document", SrcAttr: "name"},
		{Attr: "output_location.s3_bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "id"},
		{Attr: "targets.values", SrcType: "aws_instance", SrcAttr: "id"},
	},
	"aws_ssm_maintenance_window_target": {
		{Attr: "window_id", SrcType: "aws_ssm_maintenance_window", SrcAttr: "id"},
	},
	"aws_ssm_maintenance_window_task": {
		{Attr: "service_role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "targets.values", SrcType: "aws_instance", SrcAttr: "id"},
		{Attr: "window_id", SrcType: "aws_ssm_maintenance_window", SrcAttr: "id"},
	},
	"aws_ssm_patch_group": {
		{Attr: "baseline_id", SrcType: "aws_ssm_patch_baseline", SrcAttr: "id"},
	},
	"aws_ssm_resource_data_sync": {
		{Attr: "s3_destination.bucket_name", SrcType: "aws_s3_bucket", SrcAttr: "bucket"},
		{Attr: "s3_destination.region", SrcType: "aws_s3_bucket", SrcAttr: "region"},
	},
	"aws_storagegateway_cache": {
		{Attr: "gateway_arn", SrcType: "aws_storagegateway_gateway", SrcAttr: "arn"},
	},
	"aws_storagegateway_cached_iscsi_volume": {
		{Attr: "gateway_arn", SrcType: "aws_storagegateway_cache", SrcAttr: "gateway_arn"},
		{Attr: "network_interface_id", SrcType: "aws_instance", SrcAttr: "private_ip"},
		{Attr: "snapshot_id", SrcType: "aws_ebs_snapshot", SrcAttr: "id"},
		{Attr: "source_volume_arn", SrcType: "aws_storagegateway_cached_iscsi_volume", SrcAttr: "arn"},
	},
	"aws_storagegateway_gateway": {
		{Attr: "gateway_ip_address", SrcType: "aws_instance", SrcAttr: "public_ip"},
		{Attr: "smb_active_directory_settings.domain_name", SrcType: "aws_directory_service_directory", SrcAttr: "name"},
		{Attr: "smb_active_directory_settings.password", SrcType: "aws_directory_service_directory", SrcAttr: "password"},
	},
	"aws_storagegateway_nfs_file_share": {
		{Attr: "gateway_arn", SrcType: "aws_storagegateway_gateway", SrcAttr: "arn"},
		{Attr: "kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "location_arn", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_storagegateway_smb_file_share": {
		{Attr: "gateway_arn", SrcType: "aws_storagegateway_gateway", SrcAttr: "arn"},
		{Attr: "kms_key_arn", SrcType: "aws_kms_key", SrcAttr: "arn"},
		{Attr: "location_arn", SrcType: "aws_s3_bucket", SrcAttr: "arn"},
		{Attr: "role_arn", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_storagegateway_upload_buffer": {
		{Attr: "gateway_arn", SrcType: "aws_storagegateway_gateway", SrcAttr: "arn"},
	},
	"aws_storagegateway_working_storage": {
		{Attr: "gateway_arn", SrcType: "aws_storagegateway_gateway", SrcAttr: "arn"},
	},
	"aws_transfer_server": {
		{Attr: "invocation_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
		{Attr: "logging_role", SrcType: "aws_iam_role", SrcAttr: "arn"},
	},
	"aws_volume_attachment": {
		{Attr: "instance_id", SrcType: "aws_instance", SrcAttr: "id"},
		{Attr: "volume_id", SrcType: "aws_ebs_volume", SrcAttr: "id"},
	},
	"aws_vpc_dhcp_options": {
		{Attr: "domain_name", SrcType: "aws_directory_service_directory", SrcAttr: "name"},
		{Attr: "domain_name_servers", SrcType: "aws_directory_service_directory", SrcAttr: "dns_ip_addresses"},
	},
	"aws_vpc_dhcp_options_association": {
		{Attr: "dhcp_options_id", SrcType: "aws_vpc_dhcp_options", SrcAttr: "id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_vpc_endpoint": {
		{Attr: "security_group_ids", SrcType: "aws_security_group", SrcAttr: "id"},
		{Attr: "service_name", SrcType: "aws_vpc_endpoint_service", SrcAttr: "service_name"},
		{Attr: "subnet_ids", SrcType: "aws_subnet", SrcAttr: "id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_vpc_endpoint_connection_notification": {
		{Attr: "connection_notification_arn", SrcType: "aws_sns_topic", SrcAttr: "arn"},
		{Attr: "vpc_endpoint_service_id", SrcType: "aws_vpc_endpoint_service", SrcAttr: "id"},
	},
	"aws_vpc_endpoint_route_table_association": {
		{Attr: "route_table_id", SrcType: "aws_route_table", SrcAttr: "id"},
		{Attr: "vpc_endpoint_id", SrcType: "aws_vpc_endpoint", SrcAttr: "id"},
	},
	"aws_vpc_endpoint_service_allowed_principal": {
		{Attr: "vpc_endpoint_service_id", SrcType: "aws_vpc_endpoint_service", SrcAttr: "id"},
	},
	"aws_vpc_endpoint_subnet_association": {
		{Attr: "vpc_endpoint_id", SrcType: "aws_vpc_endpoint", SrcAttr: "id"},
	},
	"aws_vpc_ipv4_cidr_block_association": {
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_vpc_peering_connection": {
		{Attr: "peer_vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_vpc_peering_connection_accepter": {
		{Attr: "vpc_peering_connection_id", SrcType: "aws_vpc_peering_connection", SrcAttr: "id"},
	},
	"aws_vpn_connection": {
		{Attr: "customer_gateway_id", SrcType: "aws_customer_gateway", SrcAttr: "id"},
		{Attr: "transit_gateway_id", SrcType: "aws_ec2_transit_gateway", SrcAttr: "id"},
		{Attr: "type", SrcType: "aws_customer_gateway", SrcAttr: "type"},
		{Attr: "vpn_gateway_id", SrcType: "aws_vpn_gateway", SrcAttr: "id"},
	},
	"aws_vpn_connection_route": {
		{Attr: "vpn_connection_id", SrcType: "aws_vpn_connection", SrcAttr: "id"},
	},
	"aws_vpn_gateway": {
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
	},
	"aws_vpn_gateway_attachment": {
		{Attr: "vpc_id", SrcType: "aws_vpc", SrcAttr: "id"},
		{Attr: "vpn_gateway_id", SrcType: "aws_vpn_gateway", SrcAttr: "id"},
	},
	"aws_vpn_gateway_route_propagation": {
		{Attr: "route_table_id", SrcType: "aws_route_table", SrcAttr: "id"},
		{Attr: "vpn_gateway_id", SrcType: "aws_vpn_gateway", SrcAttr: "id"},
	},
	"aws_waf_regex_match_set": {
		{Attr: "regex_match_tuple.regex_pattern_set_id", SrcType: "aws_waf_regex_pattern_set", SrcAttr: "id"},
	},
	"aws_waf_rule_group": {
		{Attr: "activated_rule.rule_id", SrcType: "aws_waf_rule", SrcAttr: "id"},
	},
	"aws_wafregional_regex_match_set": {
		{Attr: "regex_match_tuple.regex_pattern_set_id", SrcType: "aws_wafregional_regex_pattern_set", SrcAttr: "id"},
	},
	"aws_wafregional_rule_group": {
		{Attr: "activated_rule.rule_id", SrcType: "aws_wafregional_rule", SrcAttr: "id"},
	},
	"aws_wafregional_web_acl_association": {
		{Attr: "resource_arn", SrcType: "aws_alb", SrcAttr: "arn"},
		{Attr: "web_acl_id", SrcType: "aws_wafregional_web_acl", SrcAttr: "id"},
	},
}
